irKat_shop/config/routes.rb
Rails.application.routes.draw do
  get "irkats/" => "irkats#index"

  get "irkats/new" => "irkats#new", as: :new_irkat
  post "irkats/" => "irkats#create"

  get "irkats/:id/edit" => "irkats#edit", as: :edit_irkat
  patch "irkats/:id" => "irkats#update"

  get "irkats/:id" => "irkats#show", as: :irkat

  delete "irkats/:id" => "irkats#destroy"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

irKat_shop/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

irKat_shop/app/models/irkat.rb
class Irkat < ApplicationRecord
end

irKat_shop/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

irKat_shop/app/controllers/irkats_controller.rb
class IrkatsController < ApplicationController

  before_action :set_irkat, only: [:show, :edit, :update, :destroy]

  def index
    @irkats = Irkat.all
  end

  def show
  end

  def new
    @irkat = Irkat.new
  end

  def create
    @irkat = Irkat.new(params.require(:irkat).permit(:name, :fur, :likes_ruby, :quantity))

    if @irkat.save
      redirect_to irkats_path
    else
      render :new
    end
  end

  def edit
  end

  def create
    @irkat = Irkat.new(irkat_params) # here we use our irkat_params method

    if @irkat.save
      redirect to :irkats
    else
      render :new
    end
  end

  def update

    if @irkat.update_attributes(irkat_params) #here we use our irkat_params method
      redirect_to :irkats
    else
      render :edit
    end
  end

  def destroy
    @irkat.destroy
    redirect_to irkats_path
  end

  private
  
  def irkat_params
    params.require(:irkat).permit(:name, :fur, :loves_ruby, :quantity)
  end

  def set_irkat
      @irkat = Irkat.find(params[:id])
  end

end

irKat_shop/app/helpers/application_helper.rb
module ApplicationHelper
end

irKat_shop/app/helpers/irkats_helper.rb
module IrkatsHelper
end

irKat_shop/app/views/irkats/edit.html.erb
<h1>Edit this irkat!</h1>

<%= form_for @irkat do |f| %>

    <div>
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>

    <div>
        <%= f.label :fur %>
        <%= f.text_field :fur %>
    </div>

    <div>
        <%= f.label :likes_ruby %>
        <%= f.check_box :likes_ruby, {}, 'true', 'false' %>
    </div>

    <div>
        <%= f.label :quantity %>
        <%= f.text_field :quantity %>
    </div>

    <%= f.submit "Edit your irkat!" %>

<% end %>

<%= link_to "Back to the list!", irkats_path %>

irKat_shop/app/views/irkats/index.html.erb
<h1>Today's Irkats</h1>

<ul>
    <% @irkats.each do |irkat| %>
        <li>
            <strong> <%= irkat.name %> </strong> - <%= irkat.fur %>
              <%= link_to "More info", irkat_path(irkat) %>
        </li>
    <% end %>
</ul>

irKat_shop/app/views/irkats/new.html.erb
<h1>Add a new irkat!</h1>

<%= form_for @irkat do |f| %>

    <div>
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>

    <div>
        <%= f.label :fur %>
        <%= f.text_field :fur %>
    </div>

    <div>
        <%= f.label :likes_ruby %>
        <%= f.check_box :likes_ruby, {}, 'true', 'false' %>
    </div>

    <div>
        <%= f.label :quantity %>
        <%= f.text_field :quantity %>
    </div>

    <%= f.submit "Add new irkat!" %>

<% end %>

<%= link_to "Back to the list!", irkats_path %>

irKat_shop/app/views/irkats/show.html.erb
<h1> <%= @irkat.name %> </h1>

<p>This irkat is a <%= @irkat.fur %> cub that answers <%= @irkat.likes_ruby %>, and we have <%= @irkat.quantity %> irkats available.</p>

<%= link_to "Edit this irkat!", edit_irkat_path(@irkat) %>
<%= link_to "Delete this irkat!", irkat_path, method: :delete, data: { confirm: "Are you sure you want to delete this irkat?"} %>
<%= link_to "Back to the list!", irkats_path %>

irKat_shop/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IrKat</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>